In [1]:
# Apriori Algorithm for association rule mining

In [2]:
! pip install mlxtend

In [3]:
# Importing necessary libraries

import pandas as pd
import numpy as np

In [4]:
# Reading the store data 
df = pd.read_csv("./store_data.csv",delimiter=',')
df.head(30)

shrimp          almonds        avocado    vegetables mix  \
0             burgers        meatballs           eggs               NaN   
1             chutney              NaN            NaN               NaN   
2              turkey          avocado            NaN               NaN   
3       mineral water             milk     energy bar  whole wheat rice   
4      low fat yogurt              NaN            NaN               NaN   
5   whole wheat pasta     french fries            NaN               NaN   
6                soup      light cream        shallot               NaN   
7   frozen vegetables        spaghetti      green tea               NaN   
8        french fries              NaN            NaN               NaN   
9                eggs         pet food            NaN               NaN   
10            cookies              NaN            NaN               NaN   
11             turkey          burgers  mineral water              eggs   
12          spaghetti        champagne        cookies               NaN   
13      mineral water           salmon            NaN               NaN   
14      mineral water              NaN            NaN               NaN   
15             shrimp        chocolate        chicken             honey   
16             turkey             eggs            NaN               NaN   
17             turkey       fresh tuna       tomatoes         spaghetti   
18          meatballs             milk          honey      french fries   
19           red wine           shrimp          pasta            pepper   
20               rice  sparkling water            NaN               NaN   
21          spaghetti    mineral water            ham        body spray   
22            burgers    grated cheese         shrimp             pasta   
23               eggs              NaN            NaN               NaN   
24    parmesan cheese        spaghetti           soup           avocado   
25        ground beef        spaghetti  mineral water              milk   
26    sparkling water              NaN            NaN               NaN   
27      mineral water             eggs        chicken         chocolate   
28  frozen vegetables        spaghetti           yams     mineral water   
29      herb & pepper     tomato sauce    light cream         magazines   

     green grapes whole weat flour            yams   cottage cheese  \
0             NaN              NaN             NaN              NaN   
1             NaN              NaN             NaN              NaN   
2             NaN              NaN             NaN              NaN   
3       green tea              NaN             NaN              NaN   
4             NaN              NaN             NaN              NaN   
5             NaN              NaN             NaN              NaN   
6             NaN              NaN             NaN              NaN   
7             NaN              NaN             NaN              NaN   
8             NaN              NaN             NaN              NaN   
9             NaN              NaN             NaN              NaN   
10            NaN              NaN             NaN              NaN   
11    cooking oil              NaN             NaN              NaN   
12            NaN              NaN             NaN              NaN   
13            NaN              NaN             NaN              NaN   
14            NaN              NaN             NaN              NaN   
15            oil      cooking oil  low fat yogurt              NaN   
16            NaN              NaN             NaN              NaN   
17  mineral water        black tea          salmon             eggs   
18    protein bar              NaN             NaN              NaN   
19           eggs        chocolate         shampoo              NaN   
20            NaN              NaN             NaN              NaN   
21       pancakes        green tea             NaN              NaN   
22        avocado            honey      white wine      

In [5]:
# General information about the data like shape and columns
df.shape

(7500, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   shrimp             7500 non-null   object 
 1   almonds            5746 non-null   object 
 2   avocado            4388 non-null   object 
 3   vegetables mix     3344 non-null   object 
 4   green grapes       2528 non-null   object 
 5   whole weat flour   1863 non-null   object 
 6   yams               1368 non-null   object 
 7   cottage cheese     980 non-null    object 
 8   energy drink       653 non-null    object 
 9   tomato juice       394 non-null    object 
 10  low fat yogurt     255 non-null    object 
 11  green tea          153 non-null    object 
 12  honey              86 non-null     object 
 13  salad              46 non-null     object 
 14  mineral water      24 non-null     object 
 15  salmon             7 non-null      object 
 16  antioxydant juice  3 non

In [7]:
df.columns

Index(['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes',
       'whole weat flour', 'yams', 'cottage cheese', 'energy drink',
       'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad',
       'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie',
       'spinach', 'olive oil'],
      dtype='object')

In [8]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
dataset = te.fit(df).transform(df)
dataset = dataset.astype('int')
print(dataset)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
dataset_df = pd.DataFrame(dataset)
dataset_df

0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  22  \
0      0   0   0   0   0   0   0   0   1   1  ...   1   1   1   0   0   0   0   
1      0   1   0   0   1   0   0   0   0   0  ...   0   0   1   0   0   0   0   
2      0   1   0   1   1   0   0   0   0   0  ...   0   0   0   0   0   1   0   
3      1   1   1   0   0   1   0   1   0   1  ...   0   0   1   1   0   1   0   
4      1   1   0   0   0   1   0   1   0   0  ...   1   1   1   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
7495   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
7496   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
7497   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
7498   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
7499   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

      23  24  25  
0      0   0   0  
1      0   0   0  
2      0   0   0  
3      1   0   0  
4      0   0   0  
...   ..  ..  ..  
7495   0   0   0  
7496   0   0   0  
7497   0   0   0  
7498   0   0   0  
7499   0   0   0  

[7500 rows x 26 columns]

In [10]:
from mlxtend.frequent_patterns import apriori, association_rules

In [17]:
## return the items and itemsets with at least 0.001% support
from mlxtend.frequent_patterns import apriori
apriori(dataset_df, min_support = 0.0001)

support                                        itemsets
0      0.001600                                             (0)
1      0.002000                                             (1)
2      0.000133                                             (2)
3      0.000667                                             (3)
4      0.000667                                             (4)
...         ...                                             ...
21881  0.000133     (0, 1, 4, 5, 9, 10, 14, 15, 19, 20, 23, 24)
21882  0.000133     (0, 3, 4, 5, 9, 10, 14, 15, 19, 20, 23, 24)
21883  0.000133     (0, 5, 6, 8, 9, 13, 14, 15, 17, 18, 19, 25)
21884  0.000133     (1, 3, 4, 5, 9, 10, 14, 15, 19, 20, 23, 24)
21885  0.000133  (0, 1, 3, 4, 5, 9, 10, 14, 15, 19, 20, 23, 24)

[21886 rows x 2 columns]

In [33]:
frequent_itemsets = apriori(dataset_df, min_support=0.001,use_colnames = True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

support    itemsets  length
0   0.001600         (0)       1
1   0.002000         (1)       1
2   0.001600         (5)       1
3   0.001200         (9)       1
4   0.001067        (12)       1
5   0.001067        (13)       1
6   0.001333        (14)       1
7   0.001467        (15)       1
8   0.001067        (17)       1
9   0.001333        (18)       1
10  0.001200        (19)       1
11  0.001200      (0, 1)       2
12  0.001467      (0, 5)       2
13  0.001200     (0, 19)       2
14  0.001067      (1, 5)       2
15  0.001067     (1, 15)       2
16  0.001067     (1, 18)       2
17  0.001067     (1, 19)       2
18  0.001067     (19, 5)       2
19  0.001067   (0, 1, 5)       3
20  0.001067  (0, 1, 19)       3
21  0.001067  (0, 19, 5)       3

In [27]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.001) ]

support itemsets  length
11  0.001200   (0, 1)       2
12  0.001467   (0, 5)       2
13  0.001200  (0, 19)       2
14  0.001067   (1, 5)       2
15  0.001067  (1, 15)       2
16  0.001067  (1, 18)       2
17  0.001067  (1, 19)       2
18  0.001067  (19, 5)       2

In [28]:
rules = association_rules(frequent_itemsets,metric = "lift",min_threshold=1)
rules.head()

antecedents consequents  antecedent support  consequent support   support  \
0         (0)         (1)              0.0016              0.0020  0.001200   
1         (1)         (0)              0.0020              0.0016  0.001200   
2         (0)         (5)              0.0016              0.0016  0.001467   
3         (5)         (0)              0.0016              0.0016  0.001467   
4         (0)        (19)              0.0016              0.0012  0.001200   

   confidence        lift  leverage  conviction  
0    0.750000  375.000000  0.001197      3.9920  
1    0.600000  375.000000  0.001197      2.4960  
2    0.916667  572.916667  0.001464     11.9808  
3    0.916667  572.916667  0.001464     11.9808  
4    0.750000  625.000000  0.001198      3.9952

In [30]:
rules = association_rules(frequent_itemsets, metric='confidence',min_threshold=0.4)
rules.head(10)

antecedents consequents  antecedent support  consequent support   support  \
0         (0)         (1)            0.001600            0.002000  0.001200   
1         (1)         (0)            0.002000            0.001600  0.001200   
2         (0)         (5)            0.001600            0.001600  0.001467   
3         (5)         (0)            0.001600            0.001600  0.001467   
4         (0)        (19)            0.001600            0.001200  0.001200   
5        (19)         (0)            0.001200            0.001600  0.001200   
6         (1)         (5)            0.002000            0.001600  0.001067   
7         (5)         (1)            0.001600            0.002000  0.001067   
8         (1)        (15)            0.002000            0.001467  0.001067   
9        (15)         (1)            0.001467            0.002000  0.001067   

   confidence        lift  leverage  conviction  
0    0.750000  375.000000  0.001197    3.992000  
1    0.600000  375.000000  0.001197    2.496000  
2    0.916667  572.916667  0.001464   11.980800  
3    0.916667  572.916667  0.001464   11.980800  
4    0.750000  625.000000  0.001198    3.995200  
5    1.000000  625.000000  0.001198         inf  
6    0.533333  333.333333  0.001063    2.139429  
7    0.666667  333.333333  0.001063    2.994000  
8    0.533333  363.636364  0.001064    2.139714  
9    0.727273  363.636364  0.001064    3.659333

In [31]:
rules[ (rules['lift'] > 1) & (rules['confidence'] > 0.5)]

antecedents consequents  antecedent support  consequent support   support  \
0          (0)         (1)            0.001600            0.002000  0.001200   
1          (1)         (0)            0.002000            0.001600  0.001200   
2          (0)         (5)            0.001600            0.001600  0.001467   
3          (5)         (0)            0.001600            0.001600  0.001467   
4          (0)        (19)            0.001600            0.001200  0.001200   
5         (19)         (0)            0.001200            0.001600  0.001200   
6          (1)         (5)            0.002000            0.001600  0.001067   
7          (5)         (1)            0.001600            0.002000  0.001067   
8          (1)        (15)            0.002000            0.001467  0.001067   
9         (15)         (1)            0.001467            0.002000  0.001067   
10         (1)        (18)            0.002000            0.001333  0.001067   
11        (18)         (1)            0.001333            0.002000  0.001067   
12         (1)        (19)            0.002000            0.001200  0.001067   
13        (19)         (1)            0.001200            0.002000  0.001067   
14        (19)         (5)            0.001200            0.001600  0.001067   
15         (5)        (19)            0.001600            0.001200  0.001067   
16      (0, 1)         (5)            0.001200            0.001600  0.001067   
17      (0, 5)         (1)            0.001467            0.002000  0.001067   
18      (1, 5)         (0)            0.001067            0.001600  0.001067   
19         (0)      (1, 5)            0.001600            0.001067  0.001067   
20         (1)      (0, 5)            0.002000            0.001467  0.001067   
21         (5)      (0, 1)            0.001600            0.001200  0.001067   
22      (0, 1)        (19)            0.001200            0.001200  0.001067   
23     (0, 19)         (1)            0.001200            0.002000  0.001067   
24     (1, 19)         (0)            0.001067            0.001600  0.001067   
25         (0)     (1, 19)            0.001600            0.001067  0.001067   
26         (1)     (0, 19)            0.002000            0.001200  0.001067   
27        (19)      (0, 1)            0.001200            0.001200  0.001067   
28     (0, 19)         (5)            0.001200            0.001600  0.001067   
29      (0, 5)        (19)            0.001467            0.001200  0.001067   
30     (19, 5)         (0)            0.001067            0.001600  0.001067   
31         (0)     (19, 5)            0.001600            0.001067  0.001067   
32        (19)      (0, 5)            0.001200            0.001467  0.001067   
33         (5)     (0, 19)            0.001600            0.001200  0.001067   

    confidence        lift  leverage  conviction  
0     0.750000  375.000000  0.001197    3.992000  
1     0.600000  375.000000  0.001197    2.496000  
2     0.916667  572.916667  0.001464   11.980800  
3     0.916667  572.916667  0.001464   11.980800  
4     0.750000  625.000000  0.001198    3.995200  
5     1.000000  625.000000  0.001198         inf  
6     0.533333  333.333333  0.001063    2.139429  
7     0.666667  333.333333  0.001063    2.994000  
8     0.533333  363.636364  0.001064    2.139714  
9     0.727273  363.636364  0.001064    3.659333  
10    0.533333  400.000000  0.001064    2.140000  
11    0.800000  400.000000  0.001064    4.990000  
12    0.533333  444.444444  0.001064    2.140286  
13    0.888889  444.444444  0.001064    8.982000  
14    0.888889  555.555556  0.001065    8.985600  
15    0.666667  555.555556  0.001065    2.996400  
16    0.888889  555.555556  0.001065    8.985600  
17    0.727273  363.636364  0.001064    3.659333  
18    1.000000  625.000000  0.001065         inf  
19    0.666667  625.000000  0.001065    2.996800  
20    0.533333  363.636364  0.001064    2.139714  
21    0.666667  555.555556  0.001065    2.996400  
22    0.888889  740.740741  0