In [1]:
import cv2

In [2]:
# Read color Image
path =r'image.jpeg'
img = cv2.imread(path)
#print(img)

In [3]:
# Attributes of img
#print(img)
print(type(img))
print(img.shape)
print(img[0,:10])

<class 'numpy.ndarray'>
(186, 271, 3)
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [254 254 254]
 [255 255 255]]


In [4]:
# Displaying the image
#cv2.imshow('image', img)

In [5]:
# Read grayscale Image
img_gray = cv2.imread(path, 0)

In [6]:
# Attributes of grayscale img
print(type(img_gray))
print(img_gray.shape)
print(img_gray[0,:10])

<class 'numpy.ndarray'>
(186, 271)
[255 255 255 255 255 255 255 255 254 255]


In [7]:
# Canny Edge Detection

#Canny Edge Detection is a popular edge detection algorithm.
# edge = cv2.Canny(image, minVal, maxVal)
resize_img = img
edge= cv2.Canny(resize_img,0,255)
def edge_change(val):
    minv = cv2.getTrackbarPos('min:', "Edge")
    maxv = cv2.getTrackbarPos('max:', "Edge")
    edge= cv2.Canny(resize_img,minv,maxv)
cv2.imshow("Edge",edge)
cv2.createTrackbar('min:', "Edge", 0, 255, edge_change)
cv2.createTrackbar('max:', "Edge", 0, 255, edge_change)

In [8]:
# Applying simple thresholding 

# ret, thres = cv2.threshold(source, thresholdValue, maxVal, thresholdingTechnique)
gray = img_gray
ret, thres = cv2.threshold(gray, 225, 255, cv2.THRESH_BINARY_INV)
def thres_own(val):
    thres = cv2.getTrackbarPos('thres:', "Thres")
    thr=np.where(gray>thres,0,255).astype("unit8")
    cv2.imshow("Thres",thr)
cv2.createTrackbar('thres:', "Thres", 0, 255, thres_own)
#cv2.THRESH_BINARY: If pixel intensity is greater than the set threshold, value set to 255, else set to 0 (black).
#cv2.THRESH_BINARY_INV: Inverted or Opposite case of cv2.THRESH_BINARY.

In [9]:
# Applying adaptive thresholding 

# a_thres = cv2.adaptiveThreshold(source, maxVal, adaptiveMethod, thresholdType, blocksize, constant)
# adaptive methods:  cv2.ADAPTIVE_THRESH_MEAN_C,  cv2.ADAPTIVE_THRESH_GAUSSIAN_C
a_thres =cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,9,1)
cv2.imshow("Adaptive",a_thres)

In [7]:
import cv2
import numpy as np
path =r'image.jpeg'
# load image and get dimensions
img = cv2.imread(path)

# convert to hsv
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

# threshold using inRange
range1 = (50,0,50)
range2 = (120,120,170)
mask = cv2.inRange(hsv,range1,range2)

# invert mask
mask = 255 - mask

# apply morphology closing and opening to mask
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2,2))
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

result = img.copy()
result[mask==0] = (255,255,255)

# write result to disk
cv2.imwrite("fish_mask.png", mask)
cv2.imwrite("fish_with_white_background.jpg", result)

# display it
cv2.imshow("mask", mask)
cv2.imshow("result", result)
cv2.waitKey(1)
cv2.destroyAllWindows()